check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100

reporting:
    print: summary
    reports:
        - html
        - cobertura
    dir: ./reports
    report-config:
      html:
        dir: coverage
      cobertura:
        file: cobertura-coverage.xml
